- Id: 1011103
  CardSeriesId: 1011501
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 1011104
  CardSeriesId: 1011501
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 1011105
  CardSeriesId: 1011501
  GenerationsId: 105
  SideStyleSetCharacterIds: 1031,1032,1033
- Id: 1011201
  CardSeriesId: 1011501
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033
- Id: 1011202
  CardSeriesId: 1011501
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033
- Id: 1011203
  CardSeriesId: 1011501
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033
- Id: 1011204
  CardSeriesId: 1011501
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 1020103
  CardSeriesId: 1020501
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 1020104
  CardSeriesId: 1020501
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 1020105
  CardSeriesId: 1020501
  GenerationsId: 105
  SideStyleSetCharacterIds: 1031,1032,1033,1041,1042,1043
- Id: 1020201
  CardSeriesId: 1020501
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033,1041,1042,1043
- Id: 1020202
  CardSeriesId: 1020501
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033,1041,1042,1043
- Id: 1020203
  CardSeriesId: 1020501
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033,1041,1042,1043
- Id: 1020204
  CardSeriesId: 1020501
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 1044103
  CardSeriesId: 1044401
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 1044104
  CardSeriesId: 1044401
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 1044105
  CardSeriesId: 1044401
  GenerationsId: 105
  SideStyleSetCharacterIds: 1051,1052
- Id: 1044201
  CardSeriesId: 1044401
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1051,1052
- Id: 1044202
  CardSeriesId: 1044401
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1051,1052
- Id: 1044203
  CardSeriesId: 1044401
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1051,1052
- Id: 1044204
  CardSeriesId: 1044401
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 10217011
  CardSeriesId: 1021701
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 10217012
  CardSeriesId: 1021701
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10217013
  CardSeriesId: 1021701
  GenerationsId: 105
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10217014
  CardSeriesId: 1021701
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033,1041,1042,1043
- Id: 10217015
  CardSeriesId: 1021701
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033,1041,1042,1043
- Id: 10217016
  CardSeriesId: 1021701
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033,1041,1042,1043
- Id: 10217017
  CardSeriesId: 1021701
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 10217021
  CardSeriesId: 1021702
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 10217022
  CardSeriesId: 1021702
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10217023
  CardSeriesId: 1021702
  GenerationsId: 105
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10217024
  CardSeriesId: 1021702
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033,1041,1042,1043
- Id: 10217025
  CardSeriesId: 1021702
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033,1041,1042,1043
- Id: 10217026
  CardSeriesId: 1021702
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033,1041,1042,1043
- Id: 10217027
  CardSeriesId: 1021702
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 10227011
  CardSeriesId: 1022701
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 10227012
  CardSeriesId: 1022701
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10227013
  CardSeriesId: 1022701
  GenerationsId: 105
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10227014
  CardSeriesId: 1022701
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033,1041,1042,1043
- Id: 10227015
  CardSeriesId: 1022701
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033,1041,1042,1043
- Id: 10227016
  CardSeriesId: 1022701
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033,1041,1042,1043
- Id: 10227017
  CardSeriesId: 1022701
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 10227021
  CardSeriesId: 1022702
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 10227022
  CardSeriesId: 1022702
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10227023
  CardSeriesId: 1022702
  GenerationsId: 105
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10227024
  CardSeriesId: 1022702
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033,1041,1042,1043
- Id: 10227025
  CardSeriesId: 1022702
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033,1041,1042,1043
- Id: 10227026
  CardSeriesId: 1022702
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033,1041,1042,1043
- Id: 10227027
  CardSeriesId: 1022702
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 10237011
  CardSeriesId: 1023701
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 10237012
  CardSeriesId: 1023701
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10237013
  CardSeriesId: 1023701
  GenerationsId: 105
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10237014
  CardSeriesId: 1023701
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033,1041,1042,1043
- Id: 10237015
  CardSeriesId: 1023701
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033,1041,1042,1043
- Id: 10237016
  CardSeriesId: 1023701
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033,1041,1042,1043
- Id: 10237017
  CardSeriesId: 1023701
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 10237021
  CardSeriesId: 1023702
  GenerationsId: 103
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033
- Id: 10237022
  CardSeriesId: 1023702
  GenerationsId: 104
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10237023
  CardSeriesId: 1023702
  GenerationsId: 105
  SideStyleSetCharacterIds: 1021,1022,1023,1031,1032,1033,1041,1042,1043
- Id: 10237024
  CardSeriesId: 1023702
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1021,1031,1032,1033,1041,1042,1043
- Id: 10237025
  CardSeriesId: 1023702
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1022,1031,1032,1033,1041,1042,1043
- Id: 10237026
  CardSeriesId: 1023702
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1023,1031,1032,1033,1041,1042,1043
- Id: 10237027
  CardSeriesId: 1023702
  GenerationsId: 1021
  SideStyleSetCharacterIds: 1021,1022,1023
- Id: 10335341
  CardSeriesId: 1033534
  GenerationsId: 103
  SideStyleSetCharacterIds: "1032"
- Id: 10335342
  CardSeriesId: 1033534
  GenerationsId: 104
  SideStyleSetCharacterIds: 1032,1042
- Id: 10335343
  CardSeriesId: 1033534
  GenerationsId: 105
  SideStyleSetCharacterIds: 1032,1042,1052
- Id: 10335344
  CardSeriesId: 1033534
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1032,1042,1052
- Id: 10335345
  CardSeriesId: 1033534
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1032,1042,1052
- Id: 10335346
  CardSeriesId: 1033534
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1032,1042,1052
- Id: 10435231
  CardSeriesId: 1043523
  GenerationsId: 103
  SideStyleSetCharacterIds: "1031"
- Id: 10435232
  CardSeriesId: 1043523
  GenerationsId: 104
  SideStyleSetCharacterIds: 1031,1041
- Id: 10435233
  CardSeriesId: 1043523
  GenerationsId: 105
  SideStyleSetCharacterIds: 1031,1041,1051
- Id: 10435234
  CardSeriesId: 1043523
  GenerationsId: 1051
  SideStyleSetCharacterIds: 1031,1041,1051
- Id: 10435235
  CardSeriesId: 1043523
  GenerationsId: 1052
  SideStyleSetCharacterIds: 1031,1041,1051
- Id: 10435236
  CardSeriesId: 1043523
  GenerationsId: 1053
  SideStyleSetCharacterIds: 1031,1041,1051
