- Id: 1
  VoltageLevel: 1
  MinHeartRank: 0
  MaxHeartRank: 1
  ScoreMultiplier: 0
- Id: 2
  VoltageLevel: 2
  MinHeartRank: 0
  MaxHeartRank: 1
  ScoreMultiplier: 0
- Id: 3
  VoltageLevel: 3
  MinHeartRank: 0
  MaxHeartRank: 2
  ScoreMultiplier: 0
- Id: 4
  VoltageLevel: 4
  MinHeartRank: 0
  MaxHeartRank: 2
  ScoreMultiplier: 0
- Id: 5
  VoltageLevel: 5
  MinHeartRank: 1
  MaxHeartRank: 3
  ScoreMultiplier: 0
- Id: 6
  VoltageLevel: 6
  MinHeartRank: 1
  MaxHeartRank: 3
  ScoreMultiplier: 0
- Id: 7
  VoltageLevel: 7
  MinHeartRank: 1
  MaxHeartRank: 3
  ScoreMultiplier: 0
- Id: 8
  VoltageLevel: 8
  MinHeartRank: 1
  MaxHeartRank: 4
  ScoreMultiplier: 0
- Id: 9
  VoltageLevel: 9
  MinHeartRank: 1
  MaxHeartRank: 4
  ScoreMultiplier: 0
- Id: 10
  VoltageLevel: 10
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 0
- Id: 11
  VoltageLevel: 11
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 70000
- Id: 12
  VoltageLevel: 12
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 140000
- Id: 13
  VoltageLevel: 13
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 210000
- Id: 14
  VoltageLevel: 14
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 280000
- Id: 15
  VoltageLevel: 15
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 350000
- Id: 16
  VoltageLevel: 16
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 420000
- Id: 17
  VoltageLevel: 17
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 490000
- Id: 18
  VoltageLevel: 18
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 560000
- Id: 19
  VoltageLevel: 19
  MinHeartRank: 2
  MaxHeartRank: 4
  ScoreMultiplier: 630000
- Id: 20
  VoltageLevel: 20
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 700000
- Id: 21
  VoltageLevel: 21
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 715000
- Id: 22
  VoltageLevel: 22
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 730000
- Id: 23
  VoltageLevel: 23
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 745000
- Id: 24
  VoltageLevel: 24
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 760000
- Id: 25
  VoltageLevel: 25
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 775000
- Id: 26
  VoltageLevel: 26
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 790000
- Id: 27
  VoltageLevel: 27
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 805000
- Id: 28
  VoltageLevel: 28
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 820000
- Id: 29
  VoltageLevel: 29
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 835000
- Id: 30
  VoltageLevel: 30
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 850000
- Id: 31
  VoltageLevel: 31
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 865000
- Id: 32
  VoltageLevel: 32
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 880000
- Id: 33
  VoltageLevel: 33
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 895000
- Id: 34
  VoltageLevel: 34
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 910000
- Id: 35
  VoltageLevel: 35
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 925000
- Id: 36
  VoltageLevel: 36
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 940000
- Id: 37
  VoltageLevel: 37
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 955000
- Id: 38
  VoltageLevel: 38
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 970000
- Id: 39
  VoltageLevel: 39
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 985000
- Id: 40
  VoltageLevel: 40
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1000000
- Id: 41
  VoltageLevel: 41
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1007500
- Id: 42
  VoltageLevel: 42
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1015000
- Id: 43
  VoltageLevel: 43
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1022500
- Id: 44
  VoltageLevel: 44
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1030000
- Id: 45
  VoltageLevel: 45
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1037500
- Id: 46
  VoltageLevel: 46
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1045000
- Id: 47
  VoltageLevel: 47
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1052500
- Id: 48
  VoltageLevel: 48
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1060000
- Id: 49
  VoltageLevel: 49
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1067500
- Id: 50
  VoltageLevel: 50
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1075000
- Id: 51
  VoltageLevel: 51
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1082500
- Id: 52
  VoltageLevel: 52
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1090000
- Id: 53
  VoltageLevel: 53
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1097500
- Id: 54
  VoltageLevel: 54
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1105000
- Id: 55
  VoltageLevel: 55
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1112500
- Id: 56
  VoltageLevel: 56
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1120000
- Id: 57
  VoltageLevel: 57
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1127500
- Id: 58
  VoltageLevel: 58
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1135000
- Id: 59
  VoltageLevel: 59
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1142500
- Id: 60
  VoltageLevel: 60
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1150000
- Id: 61
  VoltageLevel: 61
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1157500
- Id: 62
  VoltageLevel: 62
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1165000
- Id: 63
  VoltageLevel: 63
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1172500
- Id: 64
  VoltageLevel: 64
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1180000
- Id: 65
  VoltageLevel: 65
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1187500
- Id: 66
  VoltageLevel: 66
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1195000
- Id: 67
  VoltageLevel: 67
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1202500
- Id: 68
  VoltageLevel: 68
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1210000
- Id: 69
  VoltageLevel: 69
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1217500
- Id: 70
  VoltageLevel: 70
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1225000
- Id: 71
  VoltageLevel: 71
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1232500
- Id: 72
  VoltageLevel: 72
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1240000
- Id: 73
  VoltageLevel: 73
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1247500
- Id: 74
  VoltageLevel: 74
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1255000
- Id: 75
  VoltageLevel: 75
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1262500
- Id: 76
  VoltageLevel: 76
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1270000
- Id: 77
  VoltageLevel: 77
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1277500
- Id: 78
  VoltageLevel: 78
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1285000
- Id: 79
  VoltageLevel: 79
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1292500
- Id: 80
  VoltageLevel: 80
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1300000
- Id: 81
  VoltageLevel: 81
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1307500
- Id: 82
  VoltageLevel: 82
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1315000
- Id: 83
  VoltageLevel: 83
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1322500
- Id: 84
  VoltageLevel: 84
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1330000
- Id: 85
  VoltageLevel: 85
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1337500
- Id: 86
  VoltageLevel: 86
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1345000
- Id: 87
  VoltageLevel: 87
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1352500
- Id: 88
  VoltageLevel: 88
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1360000
- Id: 89
  VoltageLevel: 89
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1367500
- Id: 90
  VoltageLevel: 90
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1375000
- Id: 91
  VoltageLevel: 91
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1382500
- Id: 92
  VoltageLevel: 92
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1390000
- Id: 93
  VoltageLevel: 93
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1397500
- Id: 94
  VoltageLevel: 94
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1405000
- Id: 95
  VoltageLevel: 95
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1412500
- Id: 96
  VoltageLevel: 96
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1420000
- Id: 97
  VoltageLevel: 97
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1427500
- Id: 98
  VoltageLevel: 98
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1435000
- Id: 99
  VoltageLevel: 99
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1442500
- Id: 100
  VoltageLevel: 100
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1450000
- Id: 101
  VoltageLevel: 101
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1455500
- Id: 102
  VoltageLevel: 102
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1461000
- Id: 103
  VoltageLevel: 103
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1466500
- Id: 104
  VoltageLevel: 104
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1472000
- Id: 105
  VoltageLevel: 105
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1477500
- Id: 106
  VoltageLevel: 106
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1483000
- Id: 107
  VoltageLevel: 107
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1488500
- Id: 108
  VoltageLevel: 108
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1494000
- Id: 109
  VoltageLevel: 109
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1499500
- Id: 110
  VoltageLevel: 110
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1505000
- Id: 111
  VoltageLevel: 111
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1510500
- Id: 112
  VoltageLevel: 112
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1516000
- Id: 113
  VoltageLevel: 113
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1521500
- Id: 114
  VoltageLevel: 114
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1527000
- Id: 115
  VoltageLevel: 115
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1532500
- Id: 116
  VoltageLevel: 116
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1538000
- Id: 117
  VoltageLevel: 117
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1543500
- Id: 118
  VoltageLevel: 118
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1549000
- Id: 119
  VoltageLevel: 119
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1554500
- Id: 120
  VoltageLevel: 120
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1560000
- Id: 121
  VoltageLevel: 121
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1565500
- Id: 122
  VoltageLevel: 122
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1571000
- Id: 123
  VoltageLevel: 123
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1576500
- Id: 124
  VoltageLevel: 124
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1582000
- Id: 125
  VoltageLevel: 125
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1587500
- Id: 126
  VoltageLevel: 126
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1593000
- Id: 127
  VoltageLevel: 127
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1598500
- Id: 128
  VoltageLevel: 128
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1604000
- Id: 129
  VoltageLevel: 129
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1609500
- Id: 130
  VoltageLevel: 130
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1615000
- Id: 131
  VoltageLevel: 131
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1620500
- Id: 132
  VoltageLevel: 132
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1626000
- Id: 133
  VoltageLevel: 133
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1631500
- Id: 134
  VoltageLevel: 134
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1637000
- Id: 135
  VoltageLevel: 135
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1642500
- Id: 136
  VoltageLevel: 136
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1648000
- Id: 137
  VoltageLevel: 137
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1653500
- Id: 138
  VoltageLevel: 138
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1659000
- Id: 139
  VoltageLevel: 139
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1664500
- Id: 140
  VoltageLevel: 140
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1670000
- Id: 141
  VoltageLevel: 141
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1675500
- Id: 142
  VoltageLevel: 142
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1681000
- Id: 143
  VoltageLevel: 143
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1686500
- Id: 144
  VoltageLevel: 144
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1692000
- Id: 145
  VoltageLevel: 145
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1697500
- Id: 146
  VoltageLevel: 146
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1703000
- Id: 147
  VoltageLevel: 147
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1708500
- Id: 148
  VoltageLevel: 148
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1714000
- Id: 149
  VoltageLevel: 149
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1719500
- Id: 150
  VoltageLevel: 150
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1725000
- Id: 151
  VoltageLevel: 151
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1730500
- Id: 152
  VoltageLevel: 152
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1736000
- Id: 153
  VoltageLevel: 153
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1741500
- Id: 154
  VoltageLevel: 154
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1747000
- Id: 155
  VoltageLevel: 155
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1752500
- Id: 156
  VoltageLevel: 156
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1758000
- Id: 157
  VoltageLevel: 157
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1763500
- Id: 158
  VoltageLevel: 158
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1769000
- Id: 159
  VoltageLevel: 159
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1774500
- Id: 160
  VoltageLevel: 160
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1780000
- Id: 161
  VoltageLevel: 161
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1785500
- Id: 162
  VoltageLevel: 162
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1791000
- Id: 163
  VoltageLevel: 163
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1796500
- Id: 164
  VoltageLevel: 164
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1802000
- Id: 165
  VoltageLevel: 165
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1807500
- Id: 166
  VoltageLevel: 166
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1813000
- Id: 167
  VoltageLevel: 167
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1818500
- Id: 168
  VoltageLevel: 168
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1824000
- Id: 169
  VoltageLevel: 169
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1829500
- Id: 170
  VoltageLevel: 170
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1835000
- Id: 171
  VoltageLevel: 171
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1840500
- Id: 172
  VoltageLevel: 172
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1846000
- Id: 173
  VoltageLevel: 173
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1851500
- Id: 174
  VoltageLevel: 174
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1857000
- Id: 175
  VoltageLevel: 175
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1862500
- Id: 176
  VoltageLevel: 176
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1868000
- Id: 177
  VoltageLevel: 177
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1873500
- Id: 178
  VoltageLevel: 178
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1879000
- Id: 179
  VoltageLevel: 179
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1884500
- Id: 180
  VoltageLevel: 180
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1890000
- Id: 181
  VoltageLevel: 181
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1895500
- Id: 182
  VoltageLevel: 182
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1901000
- Id: 183
  VoltageLevel: 183
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1906500
- Id: 184
  VoltageLevel: 184
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1912000
- Id: 185
  VoltageLevel: 185
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1917500
- Id: 186
  VoltageLevel: 186
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1923000
- Id: 187
  VoltageLevel: 187
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1928500
- Id: 188
  VoltageLevel: 188
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1934000
- Id: 189
  VoltageLevel: 189
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1939500
- Id: 190
  VoltageLevel: 190
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1945000
- Id: 191
  VoltageLevel: 191
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1950500
- Id: 192
  VoltageLevel: 192
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1956000
- Id: 193
  VoltageLevel: 193
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1961500
- Id: 194
  VoltageLevel: 194
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1967000
- Id: 195
  VoltageLevel: 195
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1972500
- Id: 196
  VoltageLevel: 196
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1978000
- Id: 197
  VoltageLevel: 197
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1983500
- Id: 198
  VoltageLevel: 198
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1989000
- Id: 199
  VoltageLevel: 199
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 1994500
- Id: 200
  VoltageLevel: 200
  MinHeartRank: 3
  MaxHeartRank: 4
  ScoreMultiplier: 2000000
