- Id: 1
  MinTargetNum: 1
  MaxTargetNum: 100
  BaseMultiplier: 10000
  AdditionalMultiplier: 0
- Id: 2
  MinTargetNum: 101
  MaxTargetNum: 10000
  BaseMultiplier: 10100
  AdditionalMultiplier: 100
- Id: 3
  MinTargetNum: 10001
  MaxTargetNum: 100000
  BaseMultiplier: 1000010
  AdditionalMultiplier: 10
- Id: 4
  MinTargetNum: 100001
  MaxTargetNum: 200000
  BaseMultiplier: 1900010
  AdditionalMultiplier: 10
- Id: 5
  MinTargetNum: 200001
  MaxTargetNum: 1999999
  BaseMultiplier: 2900001
  AdditionalMultiplier: 1
- Id: 6
  MinTargetNum: 2000000
  MaxTargetNum: 3999999
  BaseMultiplier: 20000000
  AdditionalMultiplier: 5
- Id: 7
  MinTargetNum: 4000000
  MaxTargetNum: 5999999
  BaseMultiplier: 40000000
  AdditionalMultiplier: 5
- Id: 8
  MinTargetNum: 6000000
  MaxTargetNum: 7999999
  BaseMultiplier: 60000000
  AdditionalMultiplier: 5
- Id: 9
  MinTargetNum: 8000000
  MaxTargetNum: 9999999
  BaseMultiplier: 80000000
  AdditionalMultiplier: 5
- Id: 10
  MinTargetNum: 10000000
  MaxTargetNum: 10000000
  BaseMultiplier: 150000000
  AdditionalMultiplier: 0
